### ISSUE TITLE
I was about to make this :D

### ISSUE THREAD

**Issue by radioblahaj** [waffleprogramming/waffle-wiki#1]

**Comment by AmazingMech2418** [comment]
:)

**Comment by radioblahaj** [comment]
is waffle like scratch,, users, fourms etc?

**Comment by AmazingMech2418** [comment]
Yes. It is basically another version of Scratch. It will however allow different types of blocks and .exe exports to make apps.

**Comment by radioblahaj** [comment]
okay, can i use DinagoBB for fourms. 
We can use the scratch wiki skin

**Comment by radioblahaj** [comment]
i will use some code from the scratch wiki skin
