### ISSUE TITLE
switching to mediawiki

### ISSUE THREAD

**Issue by radioblahaj** [waffleprogramming/waffle-wiki#4]

**Comment by AmazingMech2418** [comment]
What is this?

**Comment by radioblahaj** [comment]
Mediawiki is what the scratch wiki runs on

**Comment by AmazingMech2418** [comment]
OK. Why are we switching?

**Comment by radioblahaj** [comment]
it's better inteface

**Comment by AmazingMech2418** [comment]
OK. Maybe we could have 2 wikis then.

**Comment by radioblahaj** [comment]
no, lets keep mediawiki

**Comment by AmazingMech2418** [comment]
OK. We can do both though.

**Comment by radioblahaj** [comment]
no,  like medi wiki better.
CCreated a scratch form.

**Comment by AmazingMech2418** [comment]
I said we can do both. I make one and you make the mediawiki one.

**Comment by radioblahaj** [comment]
okay

**Comment by AmazingMech2418** [comment]
Actually, we can't host PHP wikis with GH pages, so mediawiki will be deleted.

**Comment by kerrtravers** [comment]
We'll be using MediaWiki soon, however, it's not possible right now as @amazinigmech2418 said above.
