### ISSUE TITLE
CSS Helpers Needed

### ISSUE THREAD

**Issue by radioblahaj** [waffleprogramming/waffle-wiki#5]
We need help with CSS testers and coders, Please help us by working on this project, Open-source projects

**Comment by radioblahaj** [comment]
Thx

**Comment by kerrtravers** [comment]
@redmangospros In future, can you please try and watch your spelling? I've just had to go through and change the org username and any other repo's with the word "programming" in it as it was spelt wrong.

**Comment by kerrtravers** [comment]
Tracking the wiki CSS files in #7
